# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-JavaScript-DocumentWrite
version:      0.02
version_from: lib/Apache/JavaScript/DocumentWrite.pm
installdirs:  site
requires:
    mod_perl:                      1.2
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
